services:
  - docker

language: python

python:
  - "3.8"

addons:
  apt:
    packages:
      - docker-ce

before_install:
  # make local input and output directories to attach to container
  - mkdir -m 777 input output

  # useful log checks
  - readlink -f input
  - ls
  - pwd
  - uname -a
  - df -h
  - docker version

  # clone seek-testing-data
  - git clone --depth 1 https://github.com/adam2392/seek-testing-data.git

  # grab m2g's travis docker image, run it with local branch attached as a volume
#  - docker pull neuroseek/seek:latest
#  - docker images
#  - docker run -t -d --name travis -e MPLCONFIGDIR=/tmp/matplotlib -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -v $(pwd):/m2g -v $(readlink -f ../output):/output --entrypoint /bin/bash neurodata/m2g_travis:latest
#  - docker ps

# command to install dependencies
install:
  # commands to get Miniconda3 setup
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev --skip-lock

# command to run tests
script:
  - pipenv run make check
  # run test dag
#  - snakemake --config bids_root=./seek-testing-data subjects=testsubjects.tsv --snakefile ./workflow/recon_workflow/Snakefile --forceall --dag | dot -Tpdf > $(outputpath)/recon_workflow.pdf;
#  - snakemake --config bids_root=./seek-testing-data subjects=testsubjects.tsv --snakefile ./workflow/prep_localization_workflow/Snakefile --forceall --dag | dot -Tpdf > $(outputpath)/prep_localization_workflow.pdf;
#  - snakemake --config bids_root=./seek-testing-data subjects=testsubjects.tsv --snakefile ./workflow/coregistration_workflow/Snakefile --forceall --dag | dot -Tpdf > $(outputpath)/coregistration_workflow.pdf;
#  - snakemake --config bids_root=./seek-testing-data subjects=testsubjects.tsv --snakefile ./workflow/prep_vizengine_workflow/Snakefile --forceall --dag | dot -Tpdf > $(outputpath)/prep_viz_workflow.pdf;

#deploy:
#  provider: script
#  script: make build
#  on:
#    branch: master
