services:
  - docker

language: python

python:
  - "3.8"

addons:
  apt:
    packages:
      - docker-ce

before_install:
  # make local input and output directories to attach to container
  - cd ..
  - mkdir -m 777 input output

  # useful log checks
  - readlink -f input
  - ls
  - pwd
  - uname -a
  - df -h
  - docker version

  # grab m2g's travis docker image, run it with local branch attached as a volume
  - docker pull neuroseek/seek:latest
  - docker images
#  - docker run -t -d --name travis -e MPLCONFIGDIR=/tmp/matplotlib -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -v $(pwd):/m2g -v $(readlink -f ../output):/output --entrypoint /bin/bash neurodata/m2g_travis:latest
  - docker ps

# command to install dependencies
install:
  # commands to get Miniconda3 setup
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev --skip-lock

# command to run tests
script:
  - pipenv run make check
  - docker build --tag neuroseek .
  - docker run neuroseek

deploy:
  provider: script
  script: make build
  on:
    branch: master


