version: '3'
services:
  seek_workflows:
    build: 
      context: . 
      dockerfile: Dockerfile
    volumes:
      - ./data_examples:/data
    environment:
      - BIDS_ROOT=/data
      - SUBJECT=fsaverage
      - SUBJECTS_DIR=/data/
      - DERIVATIVES_OUTPUT_DIR=/data/derivatives
    tty: true  # keep container running
    container_name: 'seek'