version: 2.1

jobs:
  docs-build:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - checkout

      # Also restore pip cache to speed up installations
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pip-packages-v1-{{ .Branch }}-
            - pip-packages-v1-

      - run:
          name: Setup Python environment via Pipenv
          # ... but use latest version of EZTrack
          command: |
            sudo pip install --upgrade pip
            sudo pip install pipenv
            pipenv install --skip-lock --dev

      - run:
          name: Run unit and integration tests
          command: |
            pipenv run make check
            cd workflow/prep_localization_workflow/
            pipenv run snakemake --lint
            cd workflow/coregistration_and_viz_workflow/
            pipenv run snakemake --lint
            cd workflow/recon_workflow/
            pipenv run snakemake --lint
#            pipenv run pytest

      - save_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "~/.local/share/virtualenvs/venv"

      - run:
          name: Build the documentation
          command: |
            source activate testenv
            make build-doc

      - persist_to_workspace:
          root: doc/_build
          paths: html

      - store_artifacts:
          path: doc/_build/html/
          destination: html

  docs-deploy:
    # will only be run on master branch
    docker:
      - image: node:8.10.0
    steps:
      - checkout

      - attach_workspace:
          at: doc/_build

      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.2
            git config --global user.email "circle@seek.com"
            git config --global user.name "Circle Ci"

      - add_ssh_keys:
          fingerprints:
            - "de:75:29:a1:56:a9:53:08:b5:8f:95:c8:12:7a:bf:44"

      - run:
          # push built docs into the `dev` directory on the `gh-pages` branch
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "doc updates [skip ci]" --dist doc/_build/html --dest ./dev

workflows:
  build:
    jobs:
      - docs-build
      - docs-deploy:
          requires:
            - docs-build
          filters:
            branches:
              only: master

