#####################################################################
#  Converts neuroimages to BIDS, runs FreeSurfer reconstruction, 
#   coregistration, BIDS-derivative handling, estimation of 
#   fiducial landmarks and more.
#
# - bids_root: The root of the BIDS dataset.
# - session: The session name for datasets (see BIDS session naming).
# - SUBJECTS_DIR: The Freesurfer ``SUBJECTS_DIR`` environment variable 
#   corresponding to where results are output.
# - subjects: Where to read list of subjects in from.
#
######################################################################
# home directory that every dataset sits in -> fileutils sets the BIDS structure
bids_root:
#  "/home/adam2392/hdd/epilepsy_bids/"
#  "/home/adam2392/hdd3/sickkids/"
  '/Users/adam2392/OneDrive - Johns Hopkins/sickkids/'
#  '/Users/adam2392/Dropbox/seek_test'

# session name to give all datasets; corresponds to the ``ses-`` BIDS entity
session: "extraoperative"

# FreeSurfer variable for SUBJECTS_DIR
# when 'n/a', this will be housed in the
# ``<bids_root>/derivatives/freesurfer/`` directory
SUBJECTS_DIR: "n/a"

# the directory at which you have the seek repo in
seek_dir: ""

############# define list of subjects to run this for #############
subjects: 'subjects.tsv'

# not used
site_id: ''

############# For developers: define container URLs and paths #############
# define Docker urls to pull from for each software
acpcdetect_docker: 'docker://neuroseek/acpcdetect:2.0'
fsl_docker: 'docker://cbinyu/fsl6-core'
freesurfer_docker: 'docker://neuroseek/freesurfer7-with-mrtrix3:1.2'
blender_docker: 'docker://neuroseek/3d_reconstruction:latest'
seek_docker: 'docker://neuroseek/seek:1.0.1'
heudiconv_docker: 'docker://nipy/heudiconv:latest'
validator_docker: 'docker://bids/validator:latest'

# path for blender within mesh generator docker container
blender_path: '/usr/local/blender/blender'

# not used: extra parameters for snakemake
params:
