# home directory that every dataset sits in -> fileutils sets the BIDS structure
bids_root:
#  "/home/adam2392/hdd/epilepsy_bids/"
  '/Users/adam2392/Dropbox/epilepsy_bids'

# session name to give all datasets; corresponds to the ``ses-`` BIDS entity
session: "presurgery"

# FreeSurfer variable for SUBJECTS_DIR
# when 'n/a', this will be housed in the
# ``<bids_root>/derivatives/freesurfer/`` directory
SUBJECTS_DIR: "n/a"

############# define list of subjects to run this for #############
subjects: 'subjects.tsv'

site_id: 'clevelandnl'

############# define container URLs and paths #############
# define Docker urls to pull from for each software
acpcdetect_docker: 'docker://neuroseek/acpcdetect:2.0'
fsl_docker: 'docker://cbinyu/fsl6-core'
freesurfer_docker: 'docker://neuroseek/freesurfer7-with-mrtrix3:1.2'
blender_docker: 'docker://neuroseek/3d_reconstruction'
seek_docker: 'docker://neuroseek/seek:1.0.0'

blender_path: '/usr/local/blender/blender'

# not used: extra parameters for snakemake
params:
