# home directory that every dataset sits in -> fileutils sets the BIDS structure
bids_root:
#  "/home/ksr/Desktop/contact_localization/efri/"
#  "/Users/adam2392/Dropbox/efri/"
#  "/home/adam2392/hdd/epilepsy_bids/"
#  '/Users/adam2392/Dropbox/epilepsy_bids/'
  '/Users/adam2392/Documents/seek/data_examples/'

# session name to give all datasets; corresponds to the ``ses-`` BIDS entity
session: "presurgery"

############# define list of subjects to run this for #############
subjects: 'subjects.tsv'
#nl02	cleveland	''
#nl06	cleveland	''
#nl11	cleveland	''

blender_path: 'blender'

params:
