
############# define list of files to run this for #############
patients:
  [
    'la02'
    'umf001', 'umf002', 'umf003', 'umf005',
#    'la01', 'la02', 'la03', 'la04', 'la05', 'la06', 'la07', 'la08', 'la09', 'la10', 'la11', 'la12',
#    'la13', 'la15', 'la16', 'la17', 'la21', 'la22', 'la23', 'la24', 'la27', 'la28', 'la29', 'la31',
  ]